api = "0.7"

[buildpack]
  homepage = "https://github.com/goodrain/pnpm-install"
  id = "goodrain/pnpm-install"
  name = "Rainbond Buildpack for PNPM Install"
  version = "0.1.0"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/goodrain/pnpm-install/blob/main/LICENSE"

[metadata]
  include-files = [
    "buildpack.toml",
    "linux/amd64/bin/build",
    "linux/amd64/bin/detect",
    "linux/amd64/bin/run",
    "linux/amd64/bin/setup-symlinks",
    "linux/arm64/bin/build",
    "linux/arm64/bin/detect",
    "linux/arm64/bin/run",
    "linux/arm64/bin/setup-symlinks"
  ]

  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    name = "BP_DISABLE_SBOM"
    default = "false"
    description = "disables generation of SBOM documents during the build process"

  [[metadata.configurations]]
    name = "BP_LOG_LEVEL"
    default = "INFO"
    description = "configures buildpack output verbosity. options include INFO and DEBUG"

  [[metadata.configurations]]
	  name = "BP_NODE_PROJECT_PATH"
    description = "path to the root of the Node.js project"

	[[metadata.configurations]]
    name = "BP_PNPM_VERSION"
    description = "configures a custom pnpm version"

	[[metadata.configurations]]
    name = "BP_KEEP_NODE_BUILD_CACHE"
    default = "false"
    description = "keep the 'node_modules/.cache' folder after the build (will be readonly at runtime)'"

  [[metadata.configurations]]
	  name = "NODE_HOME"
    description = "path the Node.js installation"

  [[metadata.configurations]]
    name = "NPM_CONFIG_GLOBALCONFIG"
    description = "configures npm to read this file for global config options"

	[[metadata.configurations]]
    name = "NPM_CONFIG_LOGLEVEL"
    default = "error"
    description = "configures npm output verbosity"

  [[metadata.configurations]]
    name = "BP_PNPM_INCLUDE_BUILD_PYTHON"
    default = "false"
    description = "include python during the build process for native module compilation"


[[stacks]]
  id = "*"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
